
CXX = g++

TARGET_DIR = target
TARGET = $(TARGET_DIR)/program

SRC := $(shell find src -name "*.cpp")

all: $(TARGET)

#
$(TARGET): $(SRC) | $(TARGET_DIR)
	$(CXX) -o $(TARGET) $(SRC)


$(TARGET_DIR):
	mkdir -p $(TARGET_DIR)


clean:
	rm -rf $(TARGET_DIR)
